
POST  http://localhost:5000/soma
Content-Type: application/json

{
    "num1": 6,
    "num2": 7
}

###

GET  http://localhost:5000/calculos
Content-Type: application/json

###

DELETE  http://localhost:5000/deletar/d8a4a7a9-f2f0-443d-810b-663bc9bcdccc

###

PUT http://localhost:5000/editar/1ff65464-11e2-4b59-97fd-e91e423ac0c2
Content-Type: application/json

{
    "num1": 3,
    "num2": 9 
}