
POST  http://localhost:5000/soma
Content-Type: application/json

{
    "num1": 6,
    "num2": 7
}

###

GET  http://localhost:5000/calculos
Content-Type: application/json

###

DELETE  http://localhost:5000/deletar/296a138b-a402-41cf-8f7e-b2642489036e

###

PUT http://localhost:5000/editar/8f525e35-553d-4ec5-8c8e-5eb82ea0f9d1
Content-Type: application/json

{
    "num1": 3,
    "num2": 9 
}